export default {
  account_handle: "Account Handle",
  account_invalid_state: "Account Handle is not accessible now",
  add_to_list: "Add to List",
  change_language: "Change Language",
  compose: "Compose",
  create_list: "Create List",
  email_address: "Email Address",
  email_invalid: "Invalid Email Address",
  forgot_password: "Forgot Password",
  invalid_credentials: "Invalid Account Handle / Password",
  invite: "Invite",
  invite_impossible_now: "Cannot invite now",
  list_name: "List Name",
  list_name_placeholder: "Enter List Name",
  list_handle: "List Handle",
  list_handle_placeholder: "Enter List Handle",
  list_timeline: "List Timeline",
  lists_fetch_failed: "Failed to fetch lists",
  my_lists: "My Lists",
  network_error: "Network Error",
  password: "Password",
  publish: "Publish",
  reset: "Reset",
  sign_in: "Sign In",
  signout: "Sign Out",
  unknown_error: "Error occured",
  wrong_credentials: "Wrong Account Handle / Password",
};
