export default {
  account_added_to_list: "Account added to list",
  account_not_found: "Account not found",
  account_removed_from_list: "Account removed from list",
  account_handle: "Account Handle",
  account_invalid_state: "Account Handle is not accessible now",
  add_to_list: "Add to List",
  change_password: "Change Password",
  check_password_reset_mail:
    "Check the email associated with this account for password reset link",
  compose: "Compose",
  create_list: "Create List",
  email_address: "Email Address",
  email_invalid: "Invalid Email Address",
  forgot_password: "Forgot Password",
  invalid_credentials: "Invalid Account Handle / Password",
  invalid_password: "Invalid Password",
  invalid_old_password: "Invalid Old Password",
  invalid_new_password: "Invalid New Password",
  invite: "Invite Others",
  invite_impossible_now: "Cannot invite now",
  list_name: "List Name",
  list_name_placeholder: "Technologists",
  list_timeline: "List Timeline",
  lists_fetch_failed: "Failed to fetch lists",
  my_lists: "My Lists",
  network_error: "Network Error",
  password: "Password",
  password_existing: "Existing Password",
  password_new: "New Password",
  password_new_repeat: "Repeat New Password",
  password_change_failed: "Password change failed",
  password_changed: "Password changed",
  passwords_dont_match: "Passwords don't match",
  publish: "Publish",
  reset: "Reset",
  say_nice_things: "Say something nice",
  sign_in: "Sign In",
  signout: "Sign Out",
  unknown_error: "Error occured",
  wrong_credentials: "Wrong Account Handle / Password",
};
