export default {
  account_handle: "Account Handle",
  account_invalid_state: "Account Handle is not accessible now",
  change_language: "Change Language",
  compose: "Compose",
  create_list: "Create List",
  forgot_password: "Forgot Password",
  invalid_credentials: "Invalid Account Handle / Password",
  list_timeline: "List Timeline",
  lists_fetch_failed: "Failed to fetch lists",
  my_lists: "My Lists",
  network_error: "Network Error",
  password: "Password",
  publish: "Publish",
  reset: "Reset",
  sign_in: "Sign In",
  unknown_error: "Error occured",
  wrong_credentials: "Wrong Account Handle / Password",
};
