export default {
  account_added_to_list: "பயனர்கணக்கு பட்டியலில் சேர்க்கப்பட்டது",
  account_not_found: "பயனர்கணக்கு கிட்டவில்லை",
  account_removed_from_list: "பயனர்கணக்கு பட்டியலிலிருந்து நீக்கப்பட்டது",
  account_handle: "பயனர்கணக்கு",
  account_invalid_state: "பயனர்கணக்கு முடக்கப்பட்டுள்ளது",
  add_to_list: "பட்டியலில் சேர்",
  change_password: "கடவுச்சொல்லை மாற்று",
  check_password_reset_mail:
    "இப்பயனர்கணக்குக்குத் தொடர்பான மின்னஞ்சலைப் பார்க்கவும்",
  compose: "எழுது",
  create_list: "பட்டியல் உருவாக்கு",
  email_address: "மின்னஞ்சல் முகவரி",
  email_invalid: "தவறான மின்னஞ்சல் முகவரி",
  forgot_password: "கடவுச்சொல் மறந்ததோ",
  invalid_credentials: "பிழையான பயனர்கணக்கு / கடவுச்சொல்",
  invalid_password: "பிழையான கடவுச்சொல்",
  invite: "ஆள் சேர்",
  invite_impossible_now: "இப்போதைக்கு ஆள்சேர்க்க முடியாது",
  list_name: "பட்டியலின் பெயர்",
  list_name_placeholder: "அறிஞர்கள்",
  list_timeline: "பட்டியல் நேரக்கோடு",
  lists_fetch_failed: "பட்டியல்களைப் பெறுவதில் சிக்கல்",
  my_lists: "என் பட்டியல்கள்",
  network_error: "இணைப்பில் சிக்கல்",
  password: "கடவுச்சொல்",
  password_existing: "தற்போதைய கடவுச்சொல்",
  password_new: "புதிய கடவுச்சொல்",
  password_new_repeat: "புதிய கடவுச்சொல் மீண்டும்",
  password_change_failed: "கடவுச்சொல் மாற்றம் தோல்வியடைந்தது",
  passwords_dont_match: "கடவுச்சொற்கள் ஒன்றவில்லை",
  say_nice_things: "அல்லவை தேய அறம்பெருகும் நல்லவை நாடி இனிய சொலின்",
  sign_in: "உள்ளே போ",
  signout: "வெளியேறு",
  publish: "வெளியிடு",
  reset: "மீட்டமை",
  unknown_error: "பிழை ஏற்பட்டுள்ளது",
  wrong_credentials: "தவறான பயனர்கணக்கு / கடவுச்சொல்",
};
